// i18n dictionary (EN/IT). Keys are namespaced by component. Values may contain
// {placeholders} resolved by t(key, params). Structured values (arrays/objects)
// are read via tRaw(key). Finance/command tokens and formula notation are kept
// language-neutral on purpose (HELP, CAPM, EPS, ROE, P/E, YTM, GMV, P₀ = D₁/(r−g)…).

export type Lang = "en" | "it";

export const DICT: Record<Lang, Record<string, unknown>> = {
  en: {
    common: {
      loading: "LOADING…",
      computing: "COMPUTING…",
      optimizing: "OPTIMIZING…",
      err: "ERR",
      notAdvice: "Historical estimates — not investment advice.",
    },
    header: {
      tagline: "// OPEN BLOOMBERG TERMINAL — FREE DATA ONLY",
      local: "LOCAL",
      live: "LIVE",
      theme: "Theme: AUTO → DARK → LIGHT",
    },
    cmdbar: {
      placeholder: "Enter ticker or command — HELP for the full list",
      go: "GO ⏎",
    },
    msg: {
      loadFailed: "Load failed",
      loaded: "{sym} LOADED",
      loading: "LOADING {sym}…",
      fxFailed: "FX load failed",
      cryptoFailed: "Crypto load failed",
      termFailed: "term structure load failed",
      loadSecFirst: "LOAD A SECURITY FIRST — e.g. AAPL {cmd}",
      portfolio: "PORTFOLIO: {syms}",
      mkwzNeeds: "MKWZ NEEDS ≥2 TICKERS — e.g. MKWZ AAPL,MSFT,NVDA,JPM",
      range: "RANGE {r}",
      invalidSymbol: "INVALID SYMBOL: {sym}",
      addedWatch: "{sym} ADDED TO WATCHLIST",
      removedWatch: "{sym} REMOVED FROM WATCHLIST",
      unknown: "UNKNOWN COMMAND: {cmd} — TYPE HELP",
    },
    nav: {
      cat: { MARKET: "MARKET", INVEST: "INVESTMENTS", CORP: "CORPORATE" },
      item: {
        SEC: "SECURITY", FX: "FX", CRY: "CRYPTO", NEWS: "NEWS", HELP: "HELP",
        CAPM: "CAPM", OV: "OPTION VAL", MKWZ: "MARKOWITZ", BOND: "FIXED INC",
        EQV: "EQUITY VAL", MNA: "M&A", RGT: "RIGHTS", IPO: "IPO", OPA: "TENDER",
      },
    },
    fmt: { now: "now", min: "{n}m ago", hour: "{n}h ago", day: "{n}d ago" },
    quote: {
      title: "Security",
      empty: "Type a ticker and press ENTER — e.g. AAPL, ^GSPC, BTC-USD",
      open: "OPEN", high: "HIGH", low: "LOW", prevClose: "PREV CLOSE",
      volume: "VOLUME", high52: "52W HIGH", low52: "52W LOW", exchange: "EXCHANGE",
    },
    chart: { title: "Price Graph", loading: "LOADING…" },
    watchlist: { title: "Watchlist", empty: "Watchlist empty — ADD AAPL", sym: "Sym", last: "Last", chg: "Chg%" },
    news: { title: "News", top: "Top Stories", empty: "No headlines available" },
    fx: {
      title: "FX Monitor — ECB Reference Rates", empty: "No FX data available",
      pair: "Pair", rate: "Rate", prev: "Prev", chg: "Chg%",
    },
    crypto: {
      title: "Crypto Monitor — CoinGecko", empty: "No crypto data available",
      name: "Name", sym: "Sym", price: "Price", chg24: "24H%", mktCap: "Mkt Cap", vol24: "Vol 24H",
    },
    help: {
      title: "Help — Command Reference",
      security: "Securities", analytics: "Analytics", corpfin: "Corporate Finance",
      panels: "Panels", watchlist: "Watchlist", navigation: "Navigation — category tabs + F-keys",
      securityCmds: [
        ["<TICKER>", "Load a security (e.g. AAPL, ^GSPC, EURUSD=X, BTC-USD)"],
        ["<TICKER> GP", "Load security and focus the price graph"],
        ["1D 5D 1M 6M 1Y 5Y MAX", "Change chart range for the loaded security"],
        ["<free text>", "Search — suggestions appear while typing"],
      ],
      analyticsCmds: [
        ["<TICKER> CAPM | CAPM", "CAPM pricing: β, Jensen's α, R², E(R) vs a benchmark index"],
        ["<TICKER> OV | OV", "Option valuation: CRR binomial lattice on the GBM/Ito process + Black-Scholes"],
        ["MKWZ <T1,T2,T3…>", "Markowitz frontier: feasible region, GMV, tangency, CML, β risk classes"],
        ["BOND | YC", "US Treasury term structure + bond calculator (price/YTM, duration, convexity)"],
      ],
      corpfinCmds: [
        ["<TICKER> EQV | EQV", "Equity valuation: DDM (Gordon + 2-stage), PVGO, P/E, P/BV, div yield"],
        ["MNA", "M&A: synergies = VA(AB)−ΣVA, premium, VAN = synergies − premium"],
        ["RGT | RIGHTS", "Rights issue (ex-rights price, right value, AIAF factor) + buyback"],
        ["IPO", "IPO: bookbuilding, underpricing, money left on table, greenshoe, costs"],
        ["OPA | TENDER", "Tender offer: 30% mandatory / 90% squeeze-out, premium, defenses"],
      ],
      panelCmds: [
        ["N", "Full-screen news"],
        ["FX", "FX monitor (ECB reference rates)"],
        ["CRY", "Crypto monitor (CoinGecko top 20)"],
        ["SEC", "Back to security view"],
        ["HELP", "This screen"],
      ],
      watchlistCmds: [
        ["ADD <SYM>", "Add a symbol to the watchlist"],
        ["DEL <SYM>", "Remove a symbol from the watchlist"],
      ],
      navCats: [
        ["MARKET", "F1 Security · F2 FX · F3 Crypto · F4 News · F5 Help"],
        ["INVESTMENTS", "F1 CAPM · F2 Option Val · F3 Markowitz · F4 Fixed Inc"],
        ["CORPORATE", "F1 Equity Val · F2 M&A · F3 Rights · F4 IPO · F5 Tender"],
      ],
      note: "Data sources (all free, no API keys): Yahoo Finance public endpoints (quotes, history, search, per-symbol news), CoinGecko free API (crypto), Frankfurter.app / ECB (FX), CNBC + Yahoo Finance RSS (headlines). Quotes may be delayed 15–20 minutes depending on exchange.",
    },
    capm: {
      titleEmpty: "CAPM — Asset Pricing",
      loadFirst: "Load a security first — e.g. AAPL CAPM",
      sub: "DAILY LOG RETURNS, 1Y",
      benchmark: "BENCHMARK", riskFree: "RISK-FREE %", rfHint: "rf default = 13W T-BILL (^IRX)",
      erFormula: "E(R) CAPM = rf + β·(E(Rm) − rf)",
      beta: "BETA (β)", alpha: "JENSEN ALPHA (ann.)", r2: "R²", corr: "CORRELATION (ρ)",
      volAsset: "VOL {sym} (ann.)", volBench: "VOL BENCH (ann.)", erMarket: "E(Rm) HIST (ann.)",
      rf: "RISK-FREE", sharpe: "SHARPE (hist)", treynor: "TREYNOR (Rᴀ−rf)/β", obs: "OBSERVATIONS",
      smlTitle: "Security Market Line", smlSub: "α = ASSET RETURN − SML · β ON X",
      smlAbove: "ABOVE SML — POSITIVE ALPHA (UNDERVALUED vs CAPM)",
      smlBelow: "BELOW SML — NEGATIVE ALPHA (OVERVALUED vs CAPM)",
      smlOn: "ON THE SML — FAIRLY PRICED vs CAPM",
      note: "β and α estimated by OLS on daily log returns over the last year vs the selected benchmark; E(Rm) is the annualized historical mean of benchmark returns. Historical estimates — not investment advice.",
    },
    ov: {
      titleEmpty: "Option Valuation — Binomial Lattice",
      titleLoaded: "Option Valuation",
      loadFirst: "Load a security first — e.g. AAPL OV",
      sub: "CRR LATTICE ON GBM (ITO)",
      strike: "STRIKE", months: "MONTHS", vol: "VOL σ %", rate: "RATE r %", steps: "STEPS (≤8)",
      call: "CALL", put: "PUT", eur: "EUR", amer: "AMER",
      latticePrice: "LATTICE PRICE (N={n})", latticePrice500: "LATTICE PRICE (N=500)",
      bs: "BLACK-SCHOLES", bsEuRef: "BLACK-SCHOLES (EUR REF.)", delta: "DELTA (N=500)",
      qNeutral: "q (risk-neutral)", dt: "Δt (years)",
      parityTitle: "Put-Call Parity",
      paritySubEu: "C − P = S − K·e^(−rT) · EUROPEAN, NO DIVIDENDS",
      paritySubAm: "GAP = EARLY-EXERCISE PREMIUM OF THE AMERICAN PUT",
      parityGap: "GAP",
      empty: "Set strike, maturity, σ and r to price the option",
      note: "Cox-Ross-Rubinstein lattice: discretization of the risk-neutral Ito process dS = rS dt + σS dW. White = underlying price, amber = option value, red = early exercise optimal (American). σ defaults to the 1Y historical volatility, r to the 13W T-bill (^IRX). N=500 and Black-Scholes shown for convergence reference.",
    },
    mkwz: {
      titleEmpty: "Markowitz — Mean-Variance Frontier",
      empty: "Enter a portfolio — e.g. MKWZ AAPL,MSFT,NVDA,JPM,XOM (min 2 tickers)",
      subShort: "DAILY LOG RETURNS, 1Y · SHORT ALLOWED",
      subLong: "DAILY LOG RETURNS, 1Y · LONG ONLY",
      benchmark: "BENCHMARK (β)", riskFree: "RISK-FREE %", rfHint: "rf default = 13W T-BILL (^IRX)",
      shortSelling: "SHORT SELLING", allowed: "ALLOWED", longOnly: "LONG ONLY",
      axisRisk: "RISK σ (ann. volatility)",
      tanSharpe: "TANGENCY SHARPE", gmvRet: "GMV RET", gmvVol: "GMV VOL", tanRet: "TAN RET", tanVol: "TAN VOL",
      legendLow: "LOW β<0.8", legendMid: "MID 0.8–1.2", legendHigh: "HIGH β>1.2",
      thTicker: "TICKER", thClass: "CLASS", thwGmv: "w GMV", thwTan: "w TAN",
      noteShort: "Closed-form mean-variance frontier (Merton 1972) on annualized daily log returns, short selling allowed (Σwᵢ=1, no sign constraint).",
      noteLong: "Long-only mean-variance frontier (w≥0, Σwᵢ=1) solved numerically by projected-gradient QP over a risk-aversion sweep.",
      noteTail: "Amber curve = efficient frontier, shaded area = feasible region (dots = sampled portfolios), cyan dashed = capital market line, GMV = global minimum variance, TAN = max-Sharpe tangency. Squares are single assets colored by β risk class. Historical estimates — not investment advice.",
    },
    bond: {
      titleUs: "Fixed Income — US Treasury Term Structure",
      titleEz: "Fixed Income — Euro Area Term Structure",
      subData: "FREE PUBLIC DATA",
      market: "MARKET", usTreasury: "US TREASURY", euroArea: "EURO AREA",
      compare: "COMPARE", vs1m: "vs 1M", vs1y: "vs 1Y",
      fwd: "FORWARD", fwdBtn: "IMPLIED FWD", fwdLegend: "implied fwd",
      fwdHint: "green dashed = forwards between adjacent tenors: (1+s₂)^t₂ = (1+s₁)^t₁·(1+f)^Δt — expectations theory reads f as the expected future short rate (plus any liquidity premium). US par yields treated as spot (approx.); euro-area curve is true spot.",
      playback: "PLAYBACK", stop: "❚❚ STOP", play: "▶ PLAY",
      loadingCurve: "LOADING CURVE…",
      spread10_2: "10Y–2Y SPREAD:", curve: "CURVE:",
      shapeInverted: "INVERTED", shapeFlat: "FLAT", shapeNormal: "NORMAL", shapeNa: "n/a",
      date: "DATE", latest: "⤒ LATEST",
      spreadHistory: "10Y–2Y SPREAD HISTORY", spreadHistHint: "red = inverted (10Y < 2Y) · recession signal",
      calcTitle: "Bond Calculator", calcSub: "FIXED-COUPON, SEMI-ANNUAL DEFAULT",
      yieldToPrice: "YIELD→PRICE", priceToYtm: "PRICE→YTM",
      coupon: "COUPON %", years: "YEARS", freq: "FREQ/Y", yieldPct: "YIELD %", price: "PRICE",
      pricePer100: "PRICE (per 100)", ytm: "YTM", yieldLbl: "YIELD",
      currentYield: "CURRENT YIELD", macaulay: "MACAULAY DUR", modified: "MODIFIED DUR", convexity: "CONVEXITY",
      noPrice: "No yield solves for that price — check inputs",
      noteUs: "US Treasury par yields (Treasury.gov)", noteEz: "euro area AAA spot rates (ECB Data Portal)",
      note: "Term structure: {src}, daily. Scrub the date, overlay 1M/1Y-ago curves or hit PLAY to animate ~2y of history. 10Y–2Y inversion is a classic recession signal. Bond calculator: price = Σ coupon/(1+y/m)ᵏ + face/(1+y/m)ⁿ; YTM by bisection; modified duration = Macaulay/(1+y/m); convexity in year².",
    },
    eqv: {
      titleEmpty: "EQV — Equity Valuation",
      loadFirst: "Load a security first — e.g. AAPL EQV",
      subSec: "SEC EDGAR · FY {fy}", subManual: "MANUAL INPUTS",
      costEq: "COST OF EQ % (r)", divShare: "DIV / SHARE (D₀)", growthG1: "GROWTH g₁ %",
      terminalG2: "TERMINAL g₂ %", stage1Years: "STAGE-1 YEARS", eps: "EPS", bvps: "BVPS",
      hint: "r auto = rf + β·ERP (ERP 5.5%) · g₁ auto = (1−payout)·ROE",
      loadingFund: "LOADING FUNDAMENTALS…",
      fairVs: "DDM FAIR VALUE (2-stage) vs MARKET {price}",
      gordon: "GORDON P₀ = D₁/(r−g)", twoStage: "2-STAGE P₀", nextDiv: "NEXT DIV (D₁)",
      pvStage1: "PV STAGE-1 DIVS", pvTerminal: "PV TERMINAL", pvgo: "PVGO = P − EPS/r",
      noGrowth: "NO-GROWTH VALUE EPS/r", pe: "P / E", pbv: "P / BV", divYield: "DIVIDEND YIELD",
      roe: "ROE (SEC)", payout: "PAYOUT (SEC)",
      year: "YEAR", tvAtN: "TV@N", div: "DIV",
      sensTitle: "Fair-Value Sensitivity", sensSub: "2-STAGE DDM · vs MARKET {price}",
      undervalued: "UNDERVALUED — DDM FAIR VALUE {gap} ABOVE MARKET",
      overvalued: "OVERVALUED — DDM FAIR VALUE {gap} VS MARKET",
      fairPriced: "FAIRLY PRICED — DDM WITHIN ±10% OF MARKET",
      needDiv: "PROVIDE A DIVIDEND > 0 TO RUN THE DDM (NON-PAYERS NEED A DCF)",
      diverges: "DDM DIVERGES (r ≤ g) — RAISE COST OF EQUITY OR LOWER GROWTH",
      note: "DDM Gordon: P₀ = D₁/(r−g). Two-stage: dividends grow at g₁ for N years then at g₂ forever (Gordon terminal value discounted back). PVGO = P − EPS/r isolates the value of growth opportunities; a high P/E driven by PVGO signals a growth stock. r is the cost of equity rf + β·ERP (β from CAPM vs S&P 500, ERP 5.5%); g₁ defaults to sustainable growth (1−payout)·ROE. Fundamentals: SEC EDGAR (US filers, latest 10-K); dividends: Yahoo (TTM). All inputs editable.",
    },
    mna: {
      title: "MNA — Mergers & Acquisitions", sub: "VAN = SYNERGIES − PREMIUM",
      vaA: "VA(A) ACQUIRER", vaB: "VA(B) TARGET", vaAB: "VA(AB) COMBINED", premiumPct: "PREMIUM % ON B",
      dealHorizontal: "HORIZONTAL", dealVertical: "VERTICAL", dealConglomerate: "CONGLOMERATE",
      descHorizontal: "same industry — scale economies (e.g. DowDuPont)",
      descVertical: "supply chain — integration (e.g. EssilorLuxottica)",
      descConglomerate: "unrelated sectors — diversification (e.g. Tata)",
      vanCallout: "ACQUISITION NPV = SYNERGIES − PREMIUM",
      combinedStandalone: "COMBINED STANDALONE", synergy: "SYNERGY VA(AB)−ΣVA", synergyPct: "SYNERGY % OF TARGET",
      premiumPaid: "PREMIUM PAID", cost: "COST = VA(B)+PREMIUM", gainTarget: "GAIN TO TARGET",
      bridgeTitle: "Value Bridge", bridgeSub: "SYNERGY − PREMIUM = ACQUIRER NPV",
      barSynergy: "SYNERGY", barSynergyCap: "value created",
      barPremium: "− PREMIUM", barPremiumCap: "→ target",
      barNpv: "= NPV", barNpvCap: "→ acquirer",
      createsValue: "DEAL CREATES VALUE — ACQUIRER NPV +{npv} (synergies exceed the premium)",
      destroysValue: "DEAL DESTROYS VALUE — ACQUIRER NPV {npv} (premium exceeds synergies)",
      breakEven: "BREAK-EVEN — synergies exactly absorbed by the premium",
      note: "Synergies = VA(AB) − [VA(A) + VA(B)]: the extra value of the combined entity over the two firms standalone. The premium is the cash paid to target shareholders above market value; the target captures it. The acquirer creates value only if VAN = synergies − premium > 0, i.e. synergies are real and not overpaid for. Estimate VA(AB) by DCF on the combined cash flows. Acquisition waves cluster in rising markets with low rates.",
    },
    rgt: {
      title: "RGT — Capital Changes", sub: "RIGHTS ISSUE · BUYBACK",
      tabRights: "RIGHTS ISSUE", tabBuyback: "BUYBACK",
      oldShares: "OLD SHARES n", newShares: "NEW SHARES m", priceCum: "PRICE CUM P_cum", issuePrice: "ISSUE PRICE P_e",
      ratioHint: "subscription ratio {m}:{n} — {m} new every {n} held",
      exRightsCallout: "P_to = (n·P_cum + m·P_e)/(n+m) — THEORETICAL EX-RIGHTS PRICE",
      rightValue: "RIGHT VALUE d = P_cum−P_to", aiaf: "AIAF FACTOR K = P_to/P_cum", dilution: "DILUTION m/(n+m)",
      proceeds: "PROCEEDS / BLOCK m·P_e", discount: "DISCOUNT TO CUM", neutral: "SHAREHOLDER NEUTRAL?",
      neutralYes: "YES — value of right offsets price drop",
      rightChartTitle: "Right Value vs Issue Price", rightChartSub: "d = m·(P_cum − P_e)/(n+m) · X = P_e",
      legendRight: "d (RIGHT)",
      noteRights: "In a rights issue old shareholders receive an option (diritto) to subscribe m new shares every n held at P_e < P_cum. The stock trades down to the theoretical ex-rights price P_to; the right is worth d = P_cum − P_to, so a shareholder who sells the right is left whole. K = P_to/P_cum is the AIAF adjustment factor applied to historical prices/charts.",
      sharesOut: "SHARES OUT (M)", netIncome: "NET INCOME (M)", cashBuyback: "CASH FOR BUYBACK (M)", marketPrice: "MARKET PRICE",
      buybackHintFilled: "auto-filled from {sym} (SEC + Yahoo) · cash defaults to 1y earnings",
      buybackHint: "load a ticker to auto-fill · money in millions",
      epsAccretion: "EPS ACCRETION FROM BUYBACK",
      sharesRepurch: "SHARES REPURCHASED", pctCapital: "% OF CAPITAL", sharesAfter: "SHARES AFTER",
      epsBefore: "EPS BEFORE", epsAfter: "EPS AFTER", legalLimit: "LEGAL LIMIT (≤20% CS)",
      exceeded: "EXCEEDED", ok: "OK",
      accChartTitle: "EPS Accretion vs Buyback Size", accChartSub: "EPS ↑ AS SHARES RETIRED · X = CASH (M)",
      csLimit: "20% CS LIMIT",
      noteBuyback: "A buyback returns cash by retiring shares: with earnings fixed, fewer shares lift EPS (accretion). Italian law caps treasury shares at 20% of capital, funded from distributable reserves. Buyback vs dividend: prefer buyback when the stock looks undervalued and the firm has stable free cash flow and manageable leverage.",
    },
    ipo: {
      title: "IPO — Going Public", sub: "BOOKBUILDING · UNDERPRICING · GREENSHOE",
      descOPS: "new shares — primary, raises capital",
      descOPV: "existing shares — secondary, no new capital",
      descOPVS: "mixed — primary + secondary",
      shares: "SHARES (M)", offerPrice: "OFFER PRICE", firstClose: "1ST-DAY CLOSE", spread: "SPREAD %",
      greenshoe: "GREENSHOE %", fixedCosts: "FIXED COSTS (M)",
      rangeLow: "RANGE LOW", rangeHigh: "RANGE HIGH", oversub: "OVERSUBSCRIPTION ×",
      bookHint: "bookbuilding range + demand multiple at the low end",
      underpricingCallout: "UNDERPRICING = 1ST-DAY CLOSE / OFFER − 1",
      gross: "GROSS PROCEEDS", underSpread: "UNDERWRITING SPREAD", netIssuer: "NET TO ISSUER",
      moneyLeft: "MONEY LEFT ON TABLE", greenshoeShares: "GREENSHOE SHARES (M)", greenshoeProceeds: "GREENSHOE PROCEEDS",
      allInCost: "ALL-IN COST % OF GROSS", exmFloat: "EXM FLOAT MIN", starFloat: "STAR FLOAT MIN",
      bridgeTitle: "IPO Cost Bridge", bridgeSub: "GROSS − SPREAD − FIXED − MONEY LEFT = NET CAPTURED",
      barGross: "GROSS", barSpread: "− SPREAD", barFixed: "− FIXED", barLeft: "− LEFT", barNet: "= NET",
      sensTitle: "Offer-Price Sensitivity", sensSub: "NET PROCEEDS vs MONEY LEFT · X = OFFER PRICE",
      fairLabel: "FAIR (no $ left)", net: "NET", moneyLeftAxis: "MONEY LEFT",
      bookTitle: "Bookbuilding Demand", bookSub: "CLEARING PRICE = WHERE DEMAND MEETS SHARES OFFERED",
      sharesOffered: "SHARES OFFERED ({n}M)",
      heavyUnder: "HEAVY UNDERPRICING {pct} — large amount left on the table",
      typicalUnder: "TYPICAL UNDERPRICING {pct} — first-day pop",
      overpriced: "OVERPRICED — broke issue price on day one ({pct})",
      fairValue: "PRICED AT FAIR VALUE — no first-day move",
      note: "The offer price comes from bookbuilding (a range in the prospectus, narrowed by institutional orders). Underpricing — the first-day pop — is money left on the table for the issuer but rewards investors for taking placement risk. The greenshoe is an over-allotment option (typ. 15%) letting underwriters stabilise the price. Total cost ≈ spread (3.5–5.4%) + fixed costs + underpricing. Euronext Milan requires float ≥ 25%, 3 audited statements and a sponsor; STAR adds float ≥ 35% and governance standards.",
    },
    opa: {
      title: "OPA — Tender Offer", sub: "THRESHOLDS · PREMIUM · SQUEEZE-OUT",
      friendly: "FRIENDLY", hostile: "HOSTILE",
      friendlyHint: "agreed with the board", hostileHint: "no board agreement — defenses may apply",
      totalShares: "TOTAL SHARES (M)", currentStake: "CURRENT STAKE %", stakeSought: "STAKE SOUGHT %",
      marketPrice: "MARKET PRICE", offerPrice: "OFFER PRICE",
      hintFilled: "auto-filled from {sym} (SEC + Yahoo) · offer = +25% premium",
      hint: "load a ticker to auto-fill shares & price · shares in millions",
      premiumCallout: "BID PREMIUM = OFFER / MARKET − 1",
      sharesAcq: "SHARES TO ACQUIRE (M)", totalCost: "TOTAL COST OF BID",
      mandatory: "MANDATORY (≥30%)", triggered: "TRIGGERED", no: "NO",
      squeezeOut: "SQUEEZE-OUT (≥90%)", available: "AVAILABLE",
      equalOpp: "EQUAL-OPPORTUNITY", equalOppVal: "same price pro-quota",
      defenses: "DEFENSES", defensesHostile: "poison pill / white knight", na: "n/a",
      thresholds: [
        [30, "30% MANDATORY"], [50, "50% CONTROL"], [90, "90% SQUEEZE-OUT"], [95, "95% SELL-OUT"],
      ],
      thresholdsTitle: "Control Thresholds", thresholdsSub: "CURRENT → SOUGHT vs CONSOB LINES",
      costTitle: "Cost to Acquire vs Stake Sought", costSub: "X = STAKE % · Y = TOTAL COST",
      verdictSqueeze: "≥ 90% — SQUEEZE-OUT: right to compulsorily buy out residual minorities, then delist",
      verdictMandatory: "≥ 30% — MANDATORY TENDER OFFER triggered (CONSOB): bid must extend to all shareholders",
      verdictBelow: "BELOW 30% — voluntary partial bid, no mandatory-offer obligation",
      note: "A tender offer (OPA) is a public bid to buy shares at a fixed price, paid above market as a control premium. The law (L. 149/1992, CONSOB) balances minority protection against efficient reallocation of control. The equal-opportunity rule lets minorities sell at the same price pro-quota; crossing 30% triggers a mandatory offer to all shareholders, preventing creeping control. A hostile bid can meet defenses (poison pill, white knight, golden parachute, higher debt). Above 90% the bidder can squeeze out the residual minorities and delist.",
    },
  },
  it: {
    common: {
      loading: "CARICAMENTO…",
      computing: "CALCOLO…",
      optimizing: "OTTIMIZZAZIONE…",
      err: "ERR",
      notAdvice: "Stime storiche — non è consulenza finanziaria.",
    },
    header: {
      tagline: "// OPEN BLOOMBERG TERMINAL — SOLO DATI GRATUITI",
      local: "LOCALE",
      live: "LIVE",
      theme: "Tema: AUTO → SCURO → CHIARO",
    },
    cmdbar: {
      placeholder: "Inserisci ticker o comando — HELP per la lista completa",
      go: "VAI ⏎",
    },
    msg: {
      loadFailed: "Caricamento fallito",
      loaded: "{sym} CARICATO",
      loading: "CARICAMENTO {sym}…",
      fxFailed: "Caricamento FX fallito",
      cryptoFailed: "Caricamento crypto fallito",
      termFailed: "Caricamento struttura a termine fallito",
      loadSecFirst: "CARICA PRIMA UN TITOLO — es. AAPL {cmd}",
      portfolio: "PORTAFOGLIO: {syms}",
      mkwzNeeds: "MKWZ RICHIEDE ≥2 TICKER — es. MKWZ AAPL,MSFT,NVDA,JPM",
      range: "INTERVALLO {r}",
      invalidSymbol: "SIMBOLO NON VALIDO: {sym}",
      addedWatch: "{sym} AGGIUNTO ALLA WATCHLIST",
      removedWatch: "{sym} RIMOSSO DALLA WATCHLIST",
      unknown: "COMANDO SCONOSCIUTO: {cmd} — DIGITA HELP",
    },
    nav: {
      cat: { MARKET: "MERCATO", INVEST: "INVESTIMENTI", CORP: "SOCIETARIO" },
      item: {
        SEC: "TITOLO", FX: "FX", CRY: "CRYPTO", NEWS: "NOTIZIE", HELP: "GUIDA",
        CAPM: "CAPM", OV: "VAL. OPZIONI", MKWZ: "MARKOWITZ", BOND: "OBBLIGAZ.",
        EQV: "VAL. AZIONI", MNA: "M&A", RGT: "DIRITTI", IPO: "IPO", OPA: "OPA",
      },
    },
    fmt: { now: "ora", min: "{n}m fa", hour: "{n}h fa", day: "{n}g fa" },
    quote: {
      title: "Titolo",
      empty: "Digita un ticker e premi INVIO — es. AAPL, ^GSPC, BTC-USD",
      open: "APERTURA", high: "MASSIMO", low: "MINIMO", prevClose: "CHIUS. PREC.",
      volume: "VOLUME", high52: "MAX 52S", low52: "MIN 52S", exchange: "BORSA",
    },
    chart: { title: "Grafico Prezzo", loading: "CARICAMENTO…" },
    watchlist: { title: "Watchlist", empty: "Watchlist vuota — ADD AAPL", sym: "Simb", last: "Ultimo", chg: "Var%" },
    news: { title: "Notizie", top: "Principali", empty: "Nessuna notizia disponibile" },
    fx: {
      title: "Monitor FX — Tassi di Riferimento BCE", empty: "Nessun dato FX disponibile",
      pair: "Coppia", rate: "Tasso", prev: "Prec", chg: "Var%",
    },
    crypto: {
      title: "Monitor Crypto — CoinGecko", empty: "Nessun dato crypto disponibile",
      name: "Nome", sym: "Simb", price: "Prezzo", chg24: "24H%", mktCap: "Cap. Mkt", vol24: "Vol 24H",
    },
    help: {
      title: "Guida — Riferimento Comandi",
      security: "Titoli", analytics: "Analisi", corpfin: "Finanza Aziendale",
      panels: "Pannelli", watchlist: "Watchlist", navigation: "Navigazione — tab categorie + tasti F",
      securityCmds: [
        ["<TICKER>", "Carica un titolo (es. AAPL, ^GSPC, EURUSD=X, BTC-USD)"],
        ["<TICKER> GP", "Carica il titolo e apre il grafico prezzo"],
        ["1D 5D 1M 6M 1Y 5Y MAX", "Cambia l'intervallo del grafico per il titolo caricato"],
        ["<testo libero>", "Ricerca — i suggerimenti appaiono mentre digiti"],
      ],
      analyticsCmds: [
        ["<TICKER> CAPM | CAPM", "Pricing CAPM: β, α di Jensen, R², E(R) vs un indice benchmark"],
        ["<TICKER> OV | OV", "Valutazione opzioni: reticolo binomiale CRR sul processo GBM/Ito + Black-Scholes"],
        ["MKWZ <T1,T2,T3…>", "Frontiera di Markowitz: regione ammissibile, GMV, tangenza, CML, classi di rischio β"],
        ["BOND | YC", "Struttura a termine US Treasury + calcolatore bond (prezzo/YTM, duration, convessità)"],
      ],
      corpfinCmds: [
        ["<TICKER> EQV | EQV", "Valutazione equity: DDM (Gordon + 2 stadi), PVGO, P/E, P/BV, div yield"],
        ["MNA", "M&A: sinergie = VA(AB)−ΣVA, premio, VAN = sinergie − premio"],
        ["RGT | RIGHTS", "Aumento di capitale (prezzo ex, valore del diritto, fattore AIAF) + buyback"],
        ["IPO", "IPO: bookbuilding, underpricing, denaro lasciato sul tavolo, greenshoe, costi"],
        ["OPA | TENDER", "OPA: 30% obbligatoria / 90% squeeze-out, premio, difese"],
      ],
      panelCmds: [
        ["N", "Notizie a schermo intero"],
        ["FX", "Monitor FX (tassi di riferimento BCE)"],
        ["CRY", "Monitor crypto (CoinGecko top 20)"],
        ["SEC", "Torna alla vista titolo"],
        ["HELP", "Questa schermata"],
      ],
      watchlistCmds: [
        ["ADD <SYM>", "Aggiungi un simbolo alla watchlist"],
        ["DEL <SYM>", "Rimuovi un simbolo dalla watchlist"],
      ],
      navCats: [
        ["MERCATO", "F1 Titolo · F2 FX · F3 Crypto · F4 Notizie · F5 Guida"],
        ["INVESTIMENTI", "F1 CAPM · F2 Val. Opzioni · F3 Markowitz · F4 Obbligaz."],
        ["SOCIETARIO", "F1 Val. Azioni · F2 M&A · F3 Diritti · F4 IPO · F5 OPA"],
      ],
      note: "Fonti dati (tutte gratuite, nessuna API key): endpoint pubblici Yahoo Finance (quotazioni, storico, ricerca, notizie per simbolo), API gratuita CoinGecko (crypto), Frankfurter.app / BCE (FX), RSS CNBC + Yahoo Finance (titoli). Le quotazioni possono essere ritardate di 15–20 minuti a seconda della borsa.",
    },
    capm: {
      titleEmpty: "CAPM — Asset Pricing",
      loadFirst: "Carica prima un titolo — es. AAPL CAPM",
      sub: "RENDIMENTI LOG GIORN., 1A",
      benchmark: "BENCHMARK", riskFree: "RISK-FREE %", rfHint: "rf default = T-BILL 13S (^IRX)",
      erFormula: "E(R) CAPM = rf + β·(E(Rm) − rf)",
      beta: "BETA (β)", alpha: "ALPHA DI JENSEN (ann.)", r2: "R²", corr: "CORRELAZIONE (ρ)",
      volAsset: "VOL {sym} (ann.)", volBench: "VOL BENCH (ann.)", erMarket: "E(Rm) STORICO (ann.)",
      rf: "RISK-FREE", sharpe: "SHARPE (stor.)", treynor: "TREYNOR (Rᴀ−rf)/β", obs: "OSSERVAZIONI",
      smlTitle: "Security Market Line", smlSub: "α = RENDIMENTO ASSET − SML · β SU X",
      smlAbove: "SOPRA LA SML — ALPHA POSITIVO (SOTTOVALUTATO vs CAPM)",
      smlBelow: "SOTTO LA SML — ALPHA NEGATIVO (SOPRAVVALUTATO vs CAPM)",
      smlOn: "SULLA SML — PREZZATO CORRETTAMENTE vs CAPM",
      note: "β e α stimati per OLS su rendimenti log giornalieri dell'ultimo anno vs il benchmark selezionato; E(Rm) è la media storica annualizzata dei rendimenti del benchmark. Stime storiche — non è consulenza finanziaria.",
    },
    ov: {
      titleEmpty: "Valutazione Opzioni — Reticolo Binomiale",
      titleLoaded: "Valutazione Opzioni",
      loadFirst: "Carica prima un titolo — es. AAPL OV",
      sub: "RETICOLO CRR SU GBM (ITO)",
      strike: "STRIKE", months: "MESI", vol: "VOL σ %", rate: "TASSO r %", steps: "STEP (≤8)",
      call: "CALL", put: "PUT", eur: "EUR", amer: "AMER",
      latticePrice: "PREZZO RETICOLO (N={n})", latticePrice500: "PREZZO RETICOLO (N=500)",
      bs: "BLACK-SCHOLES", bsEuRef: "BLACK-SCHOLES (RIF. EUR)", delta: "DELTA (N=500)",
      qNeutral: "q (risk-neutral)", dt: "Δt (anni)",
      parityTitle: "Put-Call Parity",
      paritySubEu: "C − P = S − K·e^(−rT) · EUROPEE, SENZA DIVIDENDI",
      paritySubAm: "GAP = PREMIO DI ESERCIZIO ANTICIPATO DELLA PUT AMERICANA",
      parityGap: "GAP",
      empty: "Imposta strike, scadenza, σ e r per prezzare l'opzione",
      note: "Reticolo Cox-Ross-Rubinstein: discretizzazione del processo di Ito risk-neutral dS = rS dt + σS dW. Bianco = prezzo del sottostante, ambra = valore dell'opzione, rosso = esercizio anticipato ottimale (Americana). σ default = volatilità storica 1A, r = T-bill 13S (^IRX). N=500 e Black-Scholes mostrati come riferimento di convergenza.",
    },
    mkwz: {
      titleEmpty: "Markowitz — Frontiera Media-Varianza",
      empty: "Inserisci un portafoglio — es. MKWZ AAPL,MSFT,NVDA,JPM,XOM (min 2 ticker)",
      subShort: "RENDIMENTI LOG GIORN., 1A · SHORT CONSENTITO",
      subLong: "RENDIMENTI LOG GIORN., 1A · SOLO LONG",
      benchmark: "BENCHMARK (β)", riskFree: "RISK-FREE %", rfHint: "rf default = T-BILL 13S (^IRX)",
      shortSelling: "VENDITA ALLO SCOPERTO", allowed: "CONSENTITA", longOnly: "SOLO LONG",
      axisRisk: "RISCHIO σ (volatilità ann.)",
      tanSharpe: "SHARPE TANGENZA", gmvRet: "REND GMV", gmvVol: "VOL GMV", tanRet: "REND TAN", tanVol: "VOL TAN",
      legendLow: "BASSO β<0.8", legendMid: "MEDIO 0.8–1.2", legendHigh: "ALTO β>1.2",
      thTicker: "TICKER", thClass: "CLASSE", thwGmv: "w GMV", thwTan: "w TAN",
      noteShort: "Frontiera media-varianza in forma chiusa (Merton 1972) su rendimenti log giornalieri annualizzati, vendita allo scoperto consentita (Σwᵢ=1, nessun vincolo di segno).",
      noteLong: "Frontiera media-varianza solo long (w≥0, Σwᵢ=1) risolta numericamente con QP a gradiente proiettato su uno sweep di avversione al rischio.",
      noteTail: "Curva ambra = frontiera efficiente, area ombreggiata = regione ammissibile (punti = portafogli campionati), tratteggio ciano = capital market line, GMV = minima varianza globale, TAN = tangenza max-Sharpe. I quadrati sono singoli asset colorati per classe di rischio β. Stime storiche — non è consulenza finanziaria.",
    },
    bond: {
      titleUs: "Reddito Fisso — Struttura a Termine US Treasury",
      titleEz: "Reddito Fisso — Struttura a Termine Area Euro",
      subData: "DATI PUBBLICI GRATUITI",
      market: "MERCATO", usTreasury: "US TREASURY", euroArea: "AREA EURO",
      compare: "CONFRONTA", vs1m: "vs 1M", vs1y: "vs 1A",
      fwd: "FORWARD", fwdBtn: "FWD IMPLICITI", fwdLegend: "fwd impliciti",
      fwdHint: "tratteggio verde = forward tra tenor adiacenti: (1+s₂)^t₂ = (1+s₁)^t₁·(1+f)^Δt — per la teoria delle aspettative f è il tasso breve futuro atteso (più eventuale premio per la liquidità). I par yield US sono trattati come spot (approssimazione); la curva area euro è spot vera.",
      playback: "RIPRODUZIONE", stop: "❚❚ STOP", play: "▶ PLAY",
      loadingCurve: "CARICAMENTO CURVA…",
      spread10_2: "SPREAD 10Y–2Y:", curve: "CURVA:",
      shapeInverted: "INVERTITA", shapeFlat: "PIATTA", shapeNormal: "NORMALE", shapeNa: "n/d",
      date: "DATA", latest: "⤒ ULTIMA",
      spreadHistory: "STORICO SPREAD 10Y–2Y", spreadHistHint: "rosso = invertita (10Y < 2Y) · segnale di recessione",
      calcTitle: "Calcolatore Bond", calcSub: "CEDOLA FISSA, SEMESTRALE DEFAULT",
      yieldToPrice: "RENDIMENTO→PREZZO", priceToYtm: "PREZZO→YTM",
      coupon: "CEDOLA %", years: "ANNI", freq: "FREQ/A", yieldPct: "RENDIMENTO %", price: "PREZZO",
      pricePer100: "PREZZO (per 100)", ytm: "YTM", yieldLbl: "RENDIMENTO",
      currentYield: "RENDIMENTO CORRENTE", macaulay: "DUR MACAULAY", modified: "DUR MODIFICATA", convexity: "CONVESSITÀ",
      noPrice: "Nessun rendimento risolve per quel prezzo — controlla gli input",
      noteUs: "par yield US Treasury (Treasury.gov)", noteEz: "spot rate AAA area euro (ECB Data Portal)",
      note: "Struttura a termine: {src}, giornaliera. Scorri la data, sovrapponi le curve di 1M/1A fa o premi PLAY per animare ~2 anni di storia. L'inversione 10Y–2Y è un classico segnale di recessione. Calcolatore bond: prezzo = Σ cedola/(1+y/m)ᵏ + valore nominale/(1+y/m)ⁿ; YTM per bisezione; duration modificata = Macaulay/(1+y/m); convessità in anni².",
    },
    eqv: {
      titleEmpty: "EQV — Valutazione Azionaria",
      loadFirst: "Carica prima un titolo — es. AAPL EQV",
      subSec: "SEC EDGAR · ES {fy}", subManual: "INPUT MANUALI",
      costEq: "COSTO EQ % (r)", divShare: "DIV / AZIONE (D₀)", growthG1: "CRESCITA g₁ %",
      terminalG2: "TERMINALE g₂ %", stage1Years: "ANNI STADIO-1", eps: "EPS", bvps: "BVPS",
      hint: "r auto = rf + β·ERP (ERP 5.5%) · g₁ auto = (1−payout)·ROE",
      loadingFund: "CARICAMENTO FONDAMENTALI…",
      fairVs: "FAIR VALUE DDM (2 stadi) vs MERCATO {price}",
      gordon: "GORDON P₀ = D₁/(r−g)", twoStage: "P₀ 2-STADI", nextDiv: "PROSSIMO DIV (D₁)",
      pvStage1: "VA DIV STADIO-1", pvTerminal: "VA TERMINALE", pvgo: "PVGO = P − EPS/r",
      noGrowth: "VALORE NO-CRESCITA EPS/r", pe: "P / E", pbv: "P / BV", divYield: "DIVIDEND YIELD",
      roe: "ROE (SEC)", payout: "PAYOUT (SEC)",
      year: "ANNO", tvAtN: "VT@N", div: "DIV",
      sensTitle: "Sensibilità del Fair Value", sensSub: "DDM 2-STADI · vs MERCATO {price}",
      undervalued: "SOTTOVALUTATO — FAIR VALUE DDM {gap} SOPRA IL MERCATO",
      overvalued: "SOPRAVVALUTATO — FAIR VALUE DDM {gap} VS MERCATO",
      fairPriced: "PREZZATO CORRETTAMENTE — DDM ENTRO ±10% DEL MERCATO",
      needDiv: "FORNISCI UN DIVIDENDO > 0 PER ESEGUIRE IL DDM (PER I NON-PAGATORI SERVE UN DCF)",
      diverges: "IL DDM DIVERGE (r ≤ g) — AUMENTA IL COSTO DELL'EQUITY O RIDUCI LA CRESCITA",
      note: "DDM Gordon: P₀ = D₁/(r−g). Due stadi: i dividendi crescono a g₁ per N anni poi a g₂ per sempre (valore terminale di Gordon attualizzato). PVGO = P − EPS/r isola il valore delle opportunità di crescita; un P/E alto guidato dal PVGO segnala un growth stock. r è il costo dell'equity rf + β·ERP (β da CAPM vs S&P 500, ERP 5.5%); g₁ default = crescita sostenibile (1−payout)·ROE. Fondamentali: SEC EDGAR (filer USA, ultimo 10-K); dividendi: Yahoo (TTM). Tutti gli input sono modificabili.",
    },
    mna: {
      title: "MNA — Fusioni & Acquisizioni", sub: "VAN = SINERGIE − PREMIO",
      vaA: "VA(A) ACQUIRENTE", vaB: "VA(B) TARGET", vaAB: "VA(AB) COMBINATA", premiumPct: "PREMIO % SU B",
      dealHorizontal: "ORIZZONTALE", dealVertical: "VERTICALE", dealConglomerate: "CONGLOMERATA",
      descHorizontal: "stessa industria — economie di scala (es. DowDuPont)",
      descVertical: "filiera — integrazione (es. EssilorLuxottica)",
      descConglomerate: "settori non correlati — diversificazione (es. Tata)",
      vanCallout: "VAN ACQUISIZIONE = SINERGIE − PREMIO",
      combinedStandalone: "STANDALONE COMBINATA", synergy: "SINERGIA VA(AB)−ΣVA", synergyPct: "SINERGIA % DEL TARGET",
      premiumPaid: "PREMIO PAGATO", cost: "COSTO = VA(B)+PREMIO", gainTarget: "GUADAGNO PER IL TARGET",
      bridgeTitle: "Ponte del Valore", bridgeSub: "SINERGIA − PREMIO = VAN ACQUIRENTE",
      barSynergy: "SINERGIA", barSynergyCap: "valore creato",
      barPremium: "− PREMIO", barPremiumCap: "→ target",
      barNpv: "= VAN", barNpvCap: "→ acquirente",
      createsValue: "L'OPERAZIONE CREA VALORE — VAN ACQUIRENTE +{npv} (le sinergie superano il premio)",
      destroysValue: "L'OPERAZIONE DISTRUGGE VALORE — VAN ACQUIRENTE {npv} (il premio supera le sinergie)",
      breakEven: "PAREGGIO — sinergie esattamente assorbite dal premio",
      note: "Sinergie = VA(AB) − [VA(A) + VA(B)]: il valore extra dell'entità combinata rispetto alle due imprese standalone. Il premio è il contante pagato agli azionisti target sopra il valore di mercato; il target lo incassa. L'acquirente crea valore solo se VAN = sinergie − premio > 0, cioè se le sinergie sono reali e non sovrapagate. Stima VA(AB) per DCF sui flussi di cassa combinati. Le ondate di acquisizioni si concentrano in mercati in crescita con tassi bassi.",
    },
    rgt: {
      title: "RGT — Operazioni sul Capitale", sub: "AUMENTO DI CAPITALE · BUYBACK",
      tabRights: "AUMENTO DI CAPITALE", tabBuyback: "BUYBACK",
      oldShares: "AZIONI VECCHIE n", newShares: "AZIONI NUOVE m", priceCum: "PREZZO CUM P_cum", issuePrice: "PREZZO EMISS. P_e",
      ratioHint: "rapporto di sottoscrizione {m}:{n} — {m} nuove ogni {n} possedute",
      exRightsCallout: "P_to = (n·P_cum + m·P_e)/(n+m) — PREZZO TEORICO EX DIRITTO",
      rightValue: "VALORE DIRITTO d = P_cum−P_to", aiaf: "FATTORE AIAF K = P_to/P_cum", dilution: "DILUIZIONE m/(n+m)",
      proceeds: "RACCOLTA / BLOCCO m·P_e", discount: "SCONTO SU CUM", neutral: "NEUTRO PER L'AZIONISTA?",
      neutralYes: "SÌ — il valore del diritto compensa il calo del prezzo",
      rightChartTitle: "Valore del Diritto vs Prezzo di Emissione", rightChartSub: "d = m·(P_cum − P_e)/(n+m) · X = P_e",
      legendRight: "d (DIRITTO)",
      noteRights: "In un aumento di capitale i vecchi azionisti ricevono un'opzione (diritto) a sottoscrivere m azioni nuove ogni n possedute a P_e < P_cum. Il titolo scende al prezzo teorico ex diritto P_to; il diritto vale d = P_cum − P_to, quindi chi vende il diritto resta indifferente. K = P_to/P_cum è il fattore di rettifica AIAF applicato a prezzi/grafici storici.",
      sharesOut: "AZIONI IN CIRC. (M)", netIncome: "UTILE NETTO (M)", cashBuyback: "CASSA PER BUYBACK (M)", marketPrice: "PREZZO DI MERCATO",
      buybackHintFilled: "auto-compilato da {sym} (SEC + Yahoo) · cassa default = utile di 1 anno",
      buybackHint: "carica un ticker per auto-compilare · importi in milioni",
      epsAccretion: "ACCRETION EPS DA BUYBACK",
      sharesRepurch: "AZIONI RIACQUISTATE", pctCapital: "% DEL CAPITALE", sharesAfter: "AZIONI DOPO",
      epsBefore: "EPS PRIMA", epsAfter: "EPS DOPO", legalLimit: "LIMITE LEGALE (≤20% CS)",
      exceeded: "SUPERATO", ok: "OK",
      accChartTitle: "Accretion EPS vs Dimensione Buyback", accChartSub: "EPS ↑ AL RITIRO DELLE AZIONI · X = CASSA (M)",
      csLimit: "LIMITE 20% CS",
      noteBuyback: "Un buyback restituisce cassa ritirando azioni: con utili fissi, meno azioni alzano l'EPS (accretion). La legge italiana limita le azioni proprie al 20% del capitale, finanziate da riserve distribuibili. Buyback vs dividendo: preferire il buyback quando il titolo appare sottovalutato e l'impresa ha free cash flow stabile e leva gestibile.",
    },
    ipo: {
      title: "IPO — Quotazione in Borsa", sub: "BOOKBUILDING · UNDERPRICING · GREENSHOE",
      descOPS: "azioni nuove — primaria, raccoglie capitale",
      descOPV: "azioni esistenti — secondaria, nessun nuovo capitale",
      descOPVS: "mista — primaria + secondaria",
      shares: "AZIONI (M)", offerPrice: "PREZZO OFFERTA", firstClose: "CHIUS. 1° GIORNO", spread: "SPREAD %",
      greenshoe: "GREENSHOE %", fixedCosts: "COSTI FISSI (M)",
      rangeLow: "RANGE MIN", rangeHigh: "RANGE MAX", oversub: "OVERSUBSCRIPTION ×",
      bookHint: "range di bookbuilding + moltiplicatore di domanda al minimo",
      underpricingCallout: "UNDERPRICING = CHIUS. 1° GIORNO / OFFERTA − 1",
      gross: "RACCOLTA LORDA", underSpread: "SPREAD DI COLLOCAMENTO", netIssuer: "NETTO ALL'EMITTENTE",
      moneyLeft: "DENARO SUL TAVOLO", greenshoeShares: "AZIONI GREENSHOE (M)", greenshoeProceeds: "RACCOLTA GREENSHOE",
      allInCost: "COSTO TOTALE % DEL LORDO", exmFloat: "FLOTTANTE MIN EXM", starFloat: "FLOTTANTE MIN STAR",
      bridgeTitle: "Ponte dei Costi IPO", bridgeSub: "LORDO − SPREAD − FISSI − DENARO SUL TAVOLO = NETTO CATTURATO",
      barGross: "LORDO", barSpread: "− SPREAD", barFixed: "− FISSI", barLeft: "− TAVOLO", barNet: "= NETTO",
      sensTitle: "Sensibilità al Prezzo di Offerta", sensSub: "RACCOLTA NETTA vs DENARO SUL TAVOLO · X = PREZZO OFFERTA",
      fairLabel: "FAIR (niente sul tavolo)", net: "NETTO", moneyLeftAxis: "DENARO SUL TAVOLO",
      bookTitle: "Domanda di Bookbuilding", bookSub: "PREZZO DI CLEARING = DOVE LA DOMANDA INCONTRA LE AZIONI OFFERTE",
      sharesOffered: "AZIONI OFFERTE ({n}M)",
      heavyUnder: "UNDERPRICING ELEVATO {pct} — molto denaro lasciato sul tavolo",
      typicalUnder: "UNDERPRICING TIPICO {pct} — pop del primo giorno",
      overpriced: "SOVRAPPREZZATO — sotto il prezzo di emissione al primo giorno ({pct})",
      fairValue: "PREZZATO AL FAIR VALUE — nessun movimento al primo giorno",
      note: "Il prezzo di offerta nasce dal bookbuilding (un range nel prospetto, ristretto dagli ordini istituzionali). L'underpricing — il pop del primo giorno — è denaro lasciato sul tavolo per l'emittente ma premia gli investitori per il rischio di collocamento. Il greenshoe è un'opzione di over-allotment (tip. 15%) che consente ai collocatori di stabilizzare il prezzo. Costo totale ≈ spread (3.5–5.4%) + costi fissi + underpricing. Euronext Milan richiede flottante ≥ 25%, 3 bilanci certificati e uno sponsor; STAR aggiunge flottante ≥ 35% e standard di governance.",
    },
    opa: {
      title: "OPA — Offerta Pubblica di Acquisto", sub: "SOGLIE · PREMIO · SQUEEZE-OUT",
      friendly: "AMICHEVOLE", hostile: "OSTILE",
      friendlyHint: "concordata con il consiglio", hostileHint: "nessun accordo col consiglio — possibili difese",
      totalShares: "AZIONI TOTALI (M)", currentStake: "QUOTA ATTUALE %", stakeSought: "QUOTA RICERCATA %",
      marketPrice: "PREZZO DI MERCATO", offerPrice: "PREZZO DI OFFERTA",
      hintFilled: "auto-compilato da {sym} (SEC + Yahoo) · offerta = +25% premio",
      hint: "carica un ticker per auto-compilare azioni e prezzo · azioni in milioni",
      premiumCallout: "PREMIO D'OFFERTA = OFFERTA / MERCATO − 1",
      sharesAcq: "AZIONI DA ACQUISIRE (M)", totalCost: "COSTO TOTALE DELL'OFFERTA",
      mandatory: "OBBLIGATORIA (≥30%)", triggered: "ATTIVATA", no: "NO",
      squeezeOut: "SQUEEZE-OUT (≥90%)", available: "DISPONIBILE",
      equalOpp: "PARITÀ DI TRATTAMENTO", equalOppVal: "stesso prezzo pro-quota",
      defenses: "DIFESE", defensesHostile: "poison pill / cavaliere bianco", na: "n/d",
      thresholds: [
        [30, "30% OBBLIGATORIA"], [50, "50% CONTROLLO"], [90, "90% SQUEEZE-OUT"], [95, "95% SELL-OUT"],
      ],
      thresholdsTitle: "Soglie di Controllo", thresholdsSub: "ATTUALE → RICERCATA vs LINEE CONSOB",
      costTitle: "Costo di Acquisizione vs Quota Ricercata", costSub: "X = QUOTA % · Y = COSTO TOTALE",
      verdictSqueeze: "≥ 90% — SQUEEZE-OUT: diritto di acquisto coattivo delle minoranze residue, poi delisting",
      verdictMandatory: "≥ 30% — OPA OBBLIGATORIA attivata (CONSOB): l'offerta deve estendersi a tutti gli azionisti",
      verdictBelow: "SOTTO IL 30% — offerta parziale volontaria, nessun obbligo di OPA totalitaria",
      note: "Un'OPA è un'offerta pubblica di acquisto di azioni a prezzo fisso, pagato sopra il mercato come premio di controllo. La legge (L. 149/1992, CONSOB) bilancia la tutela delle minoranze con l'efficiente riallocazione del controllo. La regola di parità di trattamento consente alle minoranze di vendere allo stesso prezzo pro-quota; il superamento del 30% attiva l'offerta obbligatoria a tutti gli azionisti, prevenendo il controllo strisciante. Un'offerta ostile può incontrare difese (poison pill, cavaliere bianco, golden parachute, maggior debito). Sopra il 90% l'offerente può estromettere le minoranze residue e delistare.",
    },
  },
};
